# This is a basic workflow to help you get started with Actions

name: Documentation

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  doc:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get install -y pandoc                 
          python -m pip install --upgrade pip          
          pip install --upgrade Pygments sphinx nbsphinx sphinx_rtd_theme pandoc
          python -m pip install flake8 pytest coverage
          python -m pip install wheel setuptools cython
          python -m pip install tensorflow
          python -m pip install --upgrade nbconvert
          python -m pip install  jinja2
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
          python -m pip install -e $GITHUB_WORKSPACE
          pip install markupsafe==2.0.1
          python -m pip install ipython

      - name: Make the documentation
        run: |        
          make html
          touch _build/html/.nojekyll
        

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: _build/html/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
